### ISSUE TITLE
Commands may be standalone

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2021-hashesDB#37]
While the issues till now assume that the resulting executable will include a REPL, it should be noted that it will also be able to run standalone.

A command line like 
 
`hashes search 68522a7f7d851c7a4ccc5051e3c6aac4`

is definitely possible.

**Comment by gkosm314** [comment]
My [initial upload](https://github.com/gkosm314/gsoc2021-hashesDB/commit/e961d8393aab467fc4022cfd9e650b1ff459d309) contained such commands, so I can easily extend the commands that I included there so that they cover all the RELP commands currently proposed. Regarding the commands, do you believe that the Software Heritage related commands cover the functionalities we need?

You can find my notes for the commands [here](https://github.com/gkosm314/gsoc2021-hashesDB/blob/main/docs/commands_draft.txt).

**Comment by zvr** [comment]
Sorry, I do not monitor your own clone of this repo; I see what is being added here.

I fail to see in the doc you linked to anything about the main commands being run on the command line. I mean the major two commands `scan` and `search`, not stuff like `help`, `version`, or `stats`.

The commands should be command-line subcommands (like git, for example); keep command-line options for specifying stuff like the database (`-d` | `--database`), or other parameters (number of threads, verbose level, etc.).

**Comment by gkosm314** [comment]
Sorry, I should have pulled the changes to this repo. I merged the two repos now.
I also extended the command set so that the commands can run standalone.
